import type { Metadata } from "next";
import NavBar from "../components/navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <NavBar />
        </header>

        {children}

        <footer>
          <h2>Footer</h2>
        </footer>
      </body>
    </html>
  );
}
